// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiIvgTExeJ1Bbwc1L4tdnjMSpQRXuoqhQ',
    appId: '1:449750561021:web:88e000da6a7658f3c5ce94',
    messagingSenderId: '449750561021',
    projectId: 'autodemy-test-database',
    authDomain: 'autodemy-test-database.firebaseapp.com',
    storageBucket: 'autodemy-test-database.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiIvgTExeJ1Bbwc1L4tdnjMSpQRXuoqhQ',
    appId: '1:449750561021:android:5225378deff0c9aac5ce94',
    messagingSenderId: '449750561021',
    projectId: 'autodemy-test-database',
    storageBucket: 'autodemy-test-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiIvgTExeJ1Bbwc1L4tdnjMSpQRXuoqhQ',
    appId: '1:449750561021:ios:242be7f43da9bf6fc5ce94',
    messagingSenderId: '449750561021',
    projectId: 'autodemy-test-database',
    storageBucket: 'autodemy-test-database.firebasestorage.app',
    iosBundleId: 'com.example.autodemy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiIvgTExeJ1Bbwc1L4tdnjMSpQRXuoqhQ',
    appId: '1:449750561021:ios:242be7f43da9bf6fc5ce94',
    messagingSenderId: '449750561021',
    projectId: 'autodemy-test-database',
    storageBucket: 'autodemy-test-database.firebasestorage.app',
    iosBundleId: 'com.example.autodemy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiIvgTExeJ1Bbwc1L4tdnjMSpQRXuoqhQ',
    appId: '1:449750561021:web:d54d1a96a6ac8519c5ce94',
    messagingSenderId: '449750561021',
    projectId: 'autodemy-test-database',
    authDomain: 'autodemy-test-database.firebaseapp.com',
    storageBucket: 'autodemy-test-database.firebasestorage.app',
  );
}
